### ISSUE TITLE
Salt Worker: Get EC2 environment info from metadata or tags.

### ISSUE THREAD

**Issue by MarionTheBull** [plus3it/watchmaker#14]

**Comment by MarionTheBull** [comment]
Can I get more information on what we want for this ticket.  When I created it I didnt add any info and Im struggling to remember what we wanted from the EC2 metadata and where we wanted to put it.  :D

**Comment by lorengordon** [comment]
This was about attempting to autodetect the `enterprise_environment` grain. I don't think this is actually possible, since the account name is not part of the metadata, so I'm going to close the issue. We can re-open or re-evaluate later if we find another way. I'd also like to ditch any mention of a tri-state value for the `entenv` param. It should be `None` or a string.

**Comment by lorengordon** [comment]
Oops, forgot to actually close this previously...
